/* ═══ Dictionnaire de translittérations avec tooltips arabes ═══ */
const TRANSLIT_TOOLTIPS = [
  ["Istinjāʾ wa-Istijmār", "الاستِنجَاء والاستِجمَار"],
  ["Ḥayḍ wa-Nifās", "الحَيض والنِّفَاس"],
  ["Ḥadath Aṣghar", "الحَدَث الأَصغَر"],
  ["Ḥadath Akbar", "الحَدَث الأَكبَر"],
  ["Wuḍūʾ", "الوُضُوء"],
  ["Tayammum", "التَّيَمُّم"],
  ["Ṭahāra", "الطَّهَارَة"],
  ["Najāsa", "النَّجَاسَة"],
  ["Ḥadath", "الحَدَث"],
  ["Janāba", "الجَنَابَة"],
  ["Istinjāʾ", "الاستِنجَاء"],
  ["Ghusl", "الغُسل"],
  ["Ḥayḍ", "الحَيض"],
  ["Nifās", "النِّفَاس"],
  ["Ṣalāt al-Jumʿa", "صَلَاةُ الجُمُعَة"],
  ["Ṣalāt al-Janāza", "صَلَاةُ الجَنَازَة"],
  ["Takbīrat al-Iḥrām", "تَكبِيرَةُ الإِحرَام"],
  ["Tashahhud", "التَّشَهُّد"],
  ["Taslīm", "التَّسلِيم"],
  ["Rukūʿ", "الرُّكُوع"],
  ["Sujūd", "السُّجُود"],
  ["Fātiḥa", "الفَاتِحَة"],
  ["Iqāma", "الإِقَامَة"],
  ["Adhān", "الأَذَان"],
  ["Qibla", "القِبلَة"],
  ["Jumʿa", "الجُمُعَة"],
  ["Ṣalāt", "الصَّلَاة"],
  ["Laylat al-Qadr", "لَيلَةُ القَدر"],
  ["Ṣiyām", "الصِّيَام"],
  ["Ifṭār", "الإِفطَار"],
  ["Suḥūr", "السُّحُور"],
  ["Iʿtikāf", "الاعتِكَاف"],
  ["Ṣawm", "الصَّوم"],
  ["Zakāt al-Fiṭr", "زَكَاةُ الفِطر"],
  ["Niṣāb", "النِّصَاب"],
  ["Ḥawl", "الحَول"],
  ["Zakāt", "الزَّكَاة"],
  ["Ṭawāf al-Ifāḍa", "طَوَافُ الإِفَاضَة"],
  ["Ramy al-Jamarāt", "رَمي الجَمَرَات"],
  ["Istiṭāʿa", "الاستِطَاعَة"],
  ["Iḥrām", "الإِحرَام"],
  ["Mīqāt", "المِيقَات"],
  ["Ṭawāf", "الطَّوَاف"],
  ["Saʿy", "السَّعي"],
  ["Wuqūf", "الوُقُوف"],
  ["Talbiya", "التَّلبِيَة"],
  ["Ḥajj", "الحَجّ"],
  ["ʿUmra", "العُمرَة"],
  ["Nikāḥ", "النِّكَاح"],
  ["Ṣadāq", "الصَّدَاق"],
  ["Mahr", "المَهر"],
  ["Walī", "الوَلِيّ"],
  ["Ṭalāq Bidʿī", "الطَّلَاق البِدعِيّ"],
  ["Ṭalāq Sunnī", "الطَّلَاق السُّنِّيّ"],
  ["Ṭalāq Rajʿī", "طَلَاق رَجعِيّ"],
  ["Ṭalāq Bāʾin", "طَلَاق بَائِن"],
  ["Khulʿ", "الخُلع"],
  ["ʿIdda", "العِدَّة"],
  ["Ṭalāq", "الطَّلَاق"],
  ["Ribā al-Nasīʾa", "رِبَا النَّسِيئَة"],
  ["Ribā al-Faḍl", "رِبَا الفَضل"],
  ["Murābaḥa", "المُرَابَحَة"],
  ["Muḍāraba", "المُضَارَبَة"],
  ["Ijāra", "الإِجَارَة"],
  ["Wakāla", "الوَكَالَة"],
  ["Ribā", "الرِّبَا"],
  ["Gharar", "الغَرَر"],
  ["Farāʾiḍ", "الفَرَائِض"],
  ["Mīrāth", "المِيرَاث"],
  ["ʿAṣaba", "العَصَبَة"],
  ["Ḥudūd", "الحُدُود"],
  ["Qiṣāṣ", "القِصَاص"],
  ["Diya", "الدِّيَة"],
  ["Taʿzīr", "التَّعزِير"],
  ["Iḥsān", "الإِحسَان"],
  ["Tawba", "التَّوبَة"],
  ["Tawakkul", "التَّوَكُّل"],
  ["Maṣlaḥa al-Mursala", "المَصلَحَة المُرسَلَة"],
  ["Sadd al-Dharāʾiʿ", "سَدّ الذَّرَائِع"],
  ["ʿAmal ahl al-Madīna", "عَمَل أَهل المَدِينَة"],
  ["ʿAmal al-Madanī", "عَمَل أَهل المَدِينَة"],
  ["Istiṣḥāb", "الاستِصحَاب"],
  ["Istiḥsān", "الاستِحسَان"],
  ["Talfīq", "التَّلفِيق"],
  ["Qiyās", "القِيَاس"],
  ["Ijmāʿ", "الإِجمَاع"],
  ["Ijtihād", "الاجتِهَاد"],
  ["Maṣlaḥa", "المَصلَحَة"],
  ["Mujtahid", "المُجتَهِد"],
  ["Taqlīd", "التَّقلِيد"],
  ["Tawḥīd al-Rubūbiyya", "تَوحِيدُ الرُّبُوبِيَّة"],
  ["Tawḥīd al-Ulūhiyya", "تَوحِيدُ الأُلُوهِيَّة"],
  ["Tawḥīd al-Asmāʾ wa-l-Ṣifāt", "تَوحِيدُ الأَسمَاء والصِّفَات"],
  ["Tawḥīd", "التَّوحِيد"],
  ["Ashāʿira", "الأَشَاعِرَة"],
  ["Muʿtazila", "المُعتَزِلَة"],
  ["Bidʿa Ḥasana", "البِدعَة الحَسَنَة"],
  ["Bidʿa Sayyi'a", "البِدعَة السَّيِّئَة"],
  ["Bidʿa", "البِدعَة"],
  ["ʿIṣma", "العِصمَة"],
  ["Istiwāʾ", "الاستِوَاء"],
  ["Tafwīḍ", "التَّفوِيض"],
  ["Tajsīm", "التَّجسِيم"],
  ["Taʿṭīl", "التَّعطِيل"],
  ["Sharīʿa", "الشَّرِيعَة"],
  ["Madhhab Mālikī", "المَذهَب المَالِكِيّ"],
  ["Madhhab", "المَذهَب"],
  ["Maqāṣid al-Sharīʿa", "مَقَاصِد الشَّرِيعَة"],
  ["Ḍarūra", "الضَّرُورَة"],
  ["Ḥāja", "الحَاجَة"],
  ["Rukhṣa", "الرُّخصَة"],
  ["Niyya", "النِّيَّة"],
  ["Taqwā", "التَّقوَى"],
  ["Īmān", "الإِيمَان"],
  ["Islām", "الإِسلَام"],
  ["Fiqh", "الفِقه"],
  ["Sunna", "السُّنَّة"],
  ["Farḍ", "الفَرض"],
  ["Muwattaʾ", "المُوَطَّأ"],
  ["Mudawwana", "المُدَوَّنَة"],
  ["Hijra", "هِجرَة"],
  ["Sīra", "السِّيرَة"],
  ["Daʿwa", "الدَّعوَة"],
  ["Dār al-ʿAhd", "دَار العَهد"],
  ["Dār al-Islām", "دَار الإِسلَام"],
  ["Dār al-Ḥarb", "دَار الحَرب"],
  ["Fiqh al-Aqalliyyāt", "فِقه الأَقلِّيَّات"],
  ["Istikhlāf", "الاستِخلَاف"],
  ["Nasab", "النَّسَب"],
  ["Ḥifẓ al-Nafs", "حِفظ النَّفس"],
];


/* Applique les tooltips arabes sur un fragment HTML */
function applyArabicTooltips(html) {
  if (!html) return html;
  // Sort by length DESC to avoid partial matches
  const sorted = [...TRANSLIT_TOOLTIPS].sort((a,b) => b[0].length - a[0].length);
  let result = html;
  for (const [translit, arabic] of sorted) {
    // Don't re-wrap already wrapped terms
    const already = new RegExp('<span[^>]*data-ar=[^>]+>' + translit.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
    if (already.test(result)) continue;
    // Wrap standalone occurrences (not inside HTML tags)
    const pat = new RegExp('(?<![>\\w-])' + translit.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '(?![\\w<])', 'g');
    const span = '<span class="ar-tip" data-ar="' + arabic + '">' + translit + '</span>';
    result = result.replace(pat, span);
  }
  return result;
}
